BEGIN TRANSACTION;
DROP TABLE IF EXISTS "ACHANGE";
CREATE TABLE "ACHANGE" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZCHANGETYPE"	INTEGER,
	"ZENTITY"	INTEGER,
	"ZENTITYPK"	INTEGER,
	"ZTRANSACTIONID"	INTEGER,
	"ZCOLUMNS"	BLOB,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ATRANSACTION";
CREATE TABLE "ATRANSACTION" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZAUTHORTS"	INTEGER,
	"ZBUNDLEIDTS"	INTEGER,
	"ZCONTEXTNAMETS"	INTEGER,
	"ZPROCESSIDTS"	INTEGER,
	"ZTIMESTAMP"	FLOAT,
	"ZAUTHOR"	VARCHAR,
	"ZBUNDLEID"	VARCHAR,
	"ZCONTEXTNAME"	VARCHAR,
	"ZPROCESSID"	VARCHAR,
	"ZQUERYGEN"	BLOB,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ATRANSACTIONSTRING";
CREATE TABLE "ATRANSACTIONSTRING" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZNAME"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZCONDITION";
CREATE TABLE "ZCONDITION" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZTRIAL"	INTEGER,
	"ZNAME"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZDATABASEMETADATA";
CREATE TABLE "ZDATABASEMETADATA" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZRECORDCOUNT"	INTEGER,
	"ZCREATEDAT"	TIMESTAMP,
	"ZID"	BLOB,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZELIGIBILITY";
CREATE TABLE "ZELIGIBILITY" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZTRIAL"	INTEGER,
	"ZEXCLUSION"	VARCHAR,
	"ZINCLUSION"	VARCHAR,
	"ZRAWTEXT"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZINTERVENTION";
CREATE TABLE "ZINTERVENTION" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZTRIAL"	INTEGER,
	"ZDETAILS"	VARCHAR,
	"ZNAME"	VARCHAR,
	"ZTYPE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZLOCATION";
CREATE TABLE "ZLOCATION" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZTRIAL"	INTEGER,
	"ZCITY"	VARCHAR,
	"ZCOUNTRY"	VARCHAR,
	"ZFACILITYNAME"	VARCHAR,
	"ZPOSTALCODE"	VARCHAR,
	"ZSTATE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZLOOKUPAGERANGE";
CREATE TABLE "ZLOOKUPAGERANGE" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZVALUE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZLOOKUPCONDITION";
CREATE TABLE "ZLOOKUPCONDITION" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZVALUE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZLOOKUPCOUNTRY";
CREATE TABLE "ZLOOKUPCOUNTRY" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZVALUE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZLOOKUPGENDER";
CREATE TABLE "ZLOOKUPGENDER" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZVALUE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZLOOKUPPHASE";
CREATE TABLE "ZLOOKUPPHASE" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZVALUE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZLOOKUPSTATUS";
CREATE TABLE "ZLOOKUPSTATUS" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZVALUE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZLOOKUPSTUDYTYPE";
CREATE TABLE "ZLOOKUPSTUDYTYPE" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZVALUE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZOUTCOME";
CREATE TABLE "ZOUTCOME" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZTRIAL"	INTEGER,
	"ZDETAILS"	VARCHAR,
	"ZMEASURE"	VARCHAR,
	"ZTIMEFRAME"	VARCHAR,
	"ZTYPE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZSPONSOR";
CREATE TABLE "ZSPONSOR" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZTRIAL"	INTEGER,
	"ZAGENCYCLASS"	VARCHAR,
	"ZNAME"	VARCHAR,
	"ZROLE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "ZTRIAL";
CREATE TABLE "ZTRIAL" (
	"Z_PK"	INTEGER,
	"Z_ENT"	INTEGER,
	"Z_OPT"	INTEGER,
	"ZFDAREGULATEDDRUG"	INTEGER,
	"ZHASEXPANDEDACCESS"	INTEGER,
	"ZHASRESULTS"	INTEGER,
	"ZISFROMSYNC"	INTEGER,
	"ZELIGIBILITY"	INTEGER,
	"ZCOMPLETIONDATE"	TIMESTAMP,
	"ZLASTUPDATEPOSTDATE"	TIMESTAMP,
	"ZSTARTDATE"	TIMESTAMP,
	"ZBRIEFSUMMARY"	VARCHAR,
	"ZBRIEFTITLE"	VARCHAR,
	"ZDETAILEDDESCRIPTION"	VARCHAR,
	"ZGENDERELIGIBILITY"	VARCHAR,
	"ZMAXAGE"	VARCHAR,
	"ZMINAGE"	VARCHAR,
	"ZNCTID"	VARCHAR,
	"ZOFFICIALTITLE"	VARCHAR,
	"ZOVERALLSTATUS"	VARCHAR,
	"ZPHASE"	VARCHAR,
	"ZSTUDYTYPE"	VARCHAR,
	PRIMARY KEY("Z_PK")
);
DROP TABLE IF EXISTS "Z_METADATA";
CREATE TABLE "Z_METADATA" (
	"Z_VERSION"	INTEGER,
	"Z_UUID"	VARCHAR(255),
	"Z_PLIST"	BLOB,
	PRIMARY KEY("Z_VERSION")
);
DROP TABLE IF EXISTS "Z_MODELCACHE";
CREATE TABLE "Z_MODELCACHE" (
	"Z_CONTENT"	BLOB
);
DROP TABLE IF EXISTS "Z_PRIMARYKEY";
CREATE TABLE "Z_PRIMARYKEY" (
	"Z_ENT"	INTEGER,
	"Z_NAME"	VARCHAR,
	"Z_SUPER"	INTEGER,
	"Z_MAX"	INTEGER,
	PRIMARY KEY("Z_ENT")
);
DROP INDEX IF EXISTS "ACHANGE_ZTRANSACTIONID_INDEX";
CREATE INDEX "ACHANGE_ZTRANSACTIONID_INDEX" ON "ACHANGE" (
	"ZTRANSACTIONID"
);
DROP INDEX IF EXISTS "ATRANSACTION_ZAUTHORTS_INDEX";
CREATE INDEX "ATRANSACTION_ZAUTHORTS_INDEX" ON "ATRANSACTION" (
	"ZAUTHORTS"
);
DROP INDEX IF EXISTS "ATRANSACTION_ZBUNDLEIDTS_INDEX";
CREATE INDEX "ATRANSACTION_ZBUNDLEIDTS_INDEX" ON "ATRANSACTION" (
	"ZBUNDLEIDTS"
);
DROP INDEX IF EXISTS "ATRANSACTION_ZCONTEXTNAMETS_INDEX";
CREATE INDEX "ATRANSACTION_ZCONTEXTNAMETS_INDEX" ON "ATRANSACTION" (
	"ZCONTEXTNAMETS"
);
DROP INDEX IF EXISTS "ATRANSACTION_ZPROCESSIDTS_INDEX";
CREATE INDEX "ATRANSACTION_ZPROCESSIDTS_INDEX" ON "ATRANSACTION" (
	"ZPROCESSIDTS"
);
DROP INDEX IF EXISTS "ZCONDITION_ZTRIAL_INDEX";
CREATE INDEX "ZCONDITION_ZTRIAL_INDEX" ON "ZCONDITION" (
	"ZTRIAL"
);
DROP INDEX IF EXISTS "ZELIGIBILITY_ZTRIAL_INDEX";
CREATE INDEX "ZELIGIBILITY_ZTRIAL_INDEX" ON "ZELIGIBILITY" (
	"ZTRIAL"
);
DROP INDEX IF EXISTS "ZINTERVENTION_ZTRIAL_INDEX";
CREATE INDEX "ZINTERVENTION_ZTRIAL_INDEX" ON "ZINTERVENTION" (
	"ZTRIAL"
);
DROP INDEX IF EXISTS "ZLOCATION_ZTRIAL_INDEX";
CREATE INDEX "ZLOCATION_ZTRIAL_INDEX" ON "ZLOCATION" (
	"ZTRIAL"
);
DROP INDEX IF EXISTS "ZOUTCOME_ZTRIAL_INDEX";
CREATE INDEX "ZOUTCOME_ZTRIAL_INDEX" ON "ZOUTCOME" (
	"ZTRIAL"
);
DROP INDEX IF EXISTS "ZSPONSOR_ZTRIAL_INDEX";
CREATE INDEX "ZSPONSOR_ZTRIAL_INDEX" ON "ZSPONSOR" (
	"ZTRIAL"
);
DROP INDEX IF EXISTS "ZTRIAL_ZELIGIBILITY_INDEX";
CREATE INDEX "ZTRIAL_ZELIGIBILITY_INDEX" ON "ZTRIAL" (
	"ZELIGIBILITY"
);
DROP INDEX IF EXISTS "Z_DatabaseMetadata_UNIQUE_id";
CREATE UNIQUE INDEX "Z_DatabaseMetadata_UNIQUE_id" ON "ZDATABASEMETADATA" (
	"ZID" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_LookupAgeRange_UNIQUE_value";
CREATE UNIQUE INDEX "Z_LookupAgeRange_UNIQUE_value" ON "ZLOOKUPAGERANGE" (
	"ZVALUE" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_LookupCondition_UNIQUE_value";
CREATE UNIQUE INDEX "Z_LookupCondition_UNIQUE_value" ON "ZLOOKUPCONDITION" (
	"ZVALUE" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_LookupCountry_UNIQUE_value";
CREATE UNIQUE INDEX "Z_LookupCountry_UNIQUE_value" ON "ZLOOKUPCOUNTRY" (
	"ZVALUE" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_LookupGender_UNIQUE_value";
CREATE UNIQUE INDEX "Z_LookupGender_UNIQUE_value" ON "ZLOOKUPGENDER" (
	"ZVALUE" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_LookupPhase_UNIQUE_value";
CREATE UNIQUE INDEX "Z_LookupPhase_UNIQUE_value" ON "ZLOOKUPPHASE" (
	"ZVALUE" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_LookupStatus_UNIQUE_value";
CREATE UNIQUE INDEX "Z_LookupStatus_UNIQUE_value" ON "ZLOOKUPSTATUS" (
	"ZVALUE" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_LookupStudyType_UNIQUE_value";
CREATE UNIQUE INDEX "Z_LookupStudyType_UNIQUE_value" ON "ZLOOKUPSTUDYTYPE" (
	"ZVALUE" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_TRANSACTIONSTRING_UNIQUE_NAME";
CREATE UNIQUE INDEX "Z_TRANSACTIONSTRING_UNIQUE_NAME" ON "ATRANSACTIONSTRING" (
	"ZNAME" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_TRANSACTION_TransactionAuthorIndex";
CREATE INDEX "Z_TRANSACTION_TransactionAuthorIndex" ON "ATRANSACTION" (
	"ZAUTHOR" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_TRANSACTION_TransactionTimestampIndex";
CREATE INDEX "Z_TRANSACTION_TransactionTimestampIndex" ON "ATRANSACTION" (
	"ZTIMESTAMP" COLLATE BINARY	ASC
);
DROP INDEX IF EXISTS "Z_Trial_UNIQUE_nctId";
CREATE UNIQUE INDEX "Z_Trial_UNIQUE_nctId" ON "ZTRIAL" (
	"ZNCTID" COLLATE BINARY	ASC
);
COMMIT;
