//
//  SyncService.swift
//  nmbTrialBeacon
//
//  The clinical-trials dataset ships as a read-only bundled database that is
//  regenerated by the desktop generator app and delivered via App Store
//  updates. There is therefore no runtime import into the device database.
//
//  This service is now a thin bookkeeper: it records when the user last
//  checked for updates and surfaces the bundled snapshot's freshness. It no
//  longer mutates trial data.
//

import Foundation
import SwiftData

@MainActor
@Observable
final class SyncService {
    static let shared = SyncService()

    @ObservationIgnored private var modelContainer: ModelContainer?

    var isSyncing = false
    var syncStatus = "Up to date"
    var lastSyncDate: Date?
    var newTrialsCount = 0

    private init() {}

    func configure(container: ModelContainer) {
        self.modelContainer = container
        loadSyncMetadata()
    }

    /// Records a "checked for updates" event. The bundled dataset itself is
    /// updated through App Store releases, so this does not fetch trial data.
    func performSync(force: Bool = false) async throws {
        guard !isSyncing else { return }
        isSyncing = true
        syncStatus = "Checking…"
        defer {
            isSyncing = false
            saveSyncMetadata()
        }

        // Brief, cancellable pause so the UI shows feedback.
        try? await Task.sleep(nanoseconds: 400_000_000)

        lastSyncDate = Date()
        syncStatus = "Up to date"
    }

    func canPerformSync() -> Bool { !isSyncing && modelContainer != nil }

    // MARK: - Metadata

    private func loadSyncMetadata() {
        guard let modelContainer else { return }
        let context = ModelContext(modelContainer)
        if let data = try? context.fetch(FetchDescriptor<SyncMetadata>()).first {
            lastSyncDate = data.lastSyncDate
            newTrialsCount = data.newTrialsCount
        }
    }

    private func saveSyncMetadata() {
        guard let modelContainer else { return }
        let context = ModelContext(modelContainer)
        do {
            let existing = try context.fetch(FetchDescriptor<SyncMetadata>())
            let data: SyncMetadata
            if let first = existing.first { data = first }
            else { data = SyncMetadata(); context.insert(data) }
            data.lastSyncDate = lastSyncDate
            data.newTrialsCount = newTrialsCount
            data.isSyncing = false
            try context.save()
        } catch {
            print("⚠️ [SyncService] metadata save failed: \(error)")
        }
    }
}
